### ISSUE TITLE
SWC support (including SWC in NextJS 12)

### ISSUE THREAD

**Issue by infi-pc** [infi-pc/locatorjs#1]
**What?**
SWS is a competition to Babel. It's used in NextJS 12. Currently to use LocatorJS we have to use Babel fallback. Would be nice to benefit from SWC even when using Locator.

**How**
- [ ] Figure out how to add SWC plugins to NextJS
- [ ] Adapt our Babel plugin to SWC - seems it will be easy: https://swc.rs/docs/usage/plugins

**Comment by infi-pc** [comment]
it seems we have to wait for the support in NextJS, which seems to be postponed until there will be new plugin system in SWC https://github.com/vercel/next.js/pull/29702

**Comment by infi-pc** [comment]
solved mostly by using devtools based API variant

**Comment by aaron5670** [comment]
What about this? https://github.com/swc-project/swc/discussions/3540
