### ISSUE TITLE
bug: NextJS 13 - Warning: Extra attributes from the server: data-locator-hook-status-message

### ISSUE THREAD

**Issue by Newbie012** [infi-pc/locatorjs#114]
### Where the bug happens

- [ ] Browser Extension
- [ ] Library
- [X] Other

### your browser

Chrome

### Describe the bug

When working in NextJS 13 locally, I get:

```
app-index.js:31 Warning: Extra attributes from the server: data-locator-hook-status-message
    at head
    at html
```

### To reproduce

- Setup a new NextJS 13 app router project
- Turn on extension
- Open localhost
- See reproduction

### Additional information

While it doesn't really do anything, it hurts DX to use both LocatorJS and see this error every time, which clutters the console

**Comment by infi-pc** [comment]
Fixed with the latest release
