### ISSUE TITLE
Locator JS not working in Mac with vs code

### ISSUE THREAD

**Issue by devhiteshk** [infi-pc/locatorjs#127]
### Bug in Browser Extension

Chrome and Firefox
Locator.js was working fine previously but has now stopped functioning.

Path: vscode://file/${projectPath}${filePath}:${line}:${column}

error: user gesture required

I am able to see the components on press of command + click but doesn't take me inside vs code, previously it was working fine.

**Comment by pavleciric89** [comment]
linux ubuntu as well

**Comment by niravj-pasvtechnologies** [comment]
For me, I am being taken into vscode but file is not being opened.

**Comment by abhay0480sharma** [comment]
or me, I am being taken into vscode but file is not being opened.

**Comment by abhay0480sharma** [comment]
its a vs code latest version problem [Version 1.84]  locator js not working but in 1.83.1 its working fine

**Comment by abhay0480sharma** [comment]
> its a vs code latest version problem [Version 1.84] locator js not working but in 1.83.1 its working fine

**Comment by Mrsebastino** [comment]
I have a similar issue. It takes me to VSCode, but only to the files i have currently open. If i copy the path from from the locator and paste it in VSCode, it find the files.

**Comment by joelbqz** [comment]
Had to downgrade VSCode to 1.83.1 and worked well:
https://code.visualstudio.com/updates/v1_83

**Comment by antopolskiy** [comment]
same here

**Comment by antopolskiy** [comment]
I've found a likely cause and a temporary fix that worked for me:

The link generated by LocatorJS looks like this `vscode://file//...`. Seem that VSCode now wants the link to only be `vscode://file/...`, and in fact if you copy the link generated by LocatorJS and remove one `/`, it works.

So my solution was to switch from default VSCode settings to Custom link in the LocatorJS options. However, when I did that, I noticed that it already has only 1 `/` after `file`. But it seems that internally LocatorJS adds another slash after `file` (maybe a bug?) and I had to remove all slashes for the custom link to be generated properly in the form `vscode://file/...`. Here are my final settings:

<img width="449" alt="image" src="https://github.com/infi-pc/locatorjs/assets/23148726/6e9fab42-3b41-46d3-b96e-ac226d553130">

This now properly opens VSCode on the correct line. However, right now I have the issue that VSCode keeps asking me if I want to open the link, even though I mark "Allow opening links without asking". If someone has a fix for that, would be appreciated.

**Comment by OmegaNalphA** [comment]
The workaround listed here worked for me a little, but vscode keeps showing me a warning, even when I click "Allow opening local paths without asking
![image](https://github.com/infi-pc/locatorjs/assets/10100874/f4657fbf-1410-4fc9-819d-8a2921604c62)

**Comment by zer0thbit** [comment]
> The workaround listed here worked for me a little, but vscode keeps showing me a warning, even when I click "Allow opening local paths without asking ![image](https://user-images.githubusercontent.com/10100874/281570036-f4657fbf-1410-4fc9-819d-8a2921604c62.png)

Simply tick the checkbox at the bottom.

**Comment by zer0thbit** [comment]
> I've found a likely cause and a temporary fix that worked for me:
> 
> The link generated by LocatorJS looks like this `vscode://file//...`. Seem that VSCode now wants the link to only be `vscode://file/...`, and in fact if you copy the link generated by LocatorJS and remove one `/`, it works.
> 
> So my solution was to switch from default VSCode settings to Custom link in the LocatorJS options. However, when I did that, I noticed that it already has only 1 `/` after `file`. But it seems that internally LocatorJS adds another slash after `file` (maybe a bug? or perhaps `${projectPath}` has a slash in front of it) and I had to remove all slashes after `file` for the custom link to be generated properly in the form `vscode://file/...`. Here are my final settings:
> 
> <img alt="image" width="449" src="https://user-images.githubusercontent.com/23148726/281286132-6e9fab42-3b41-46d3-b96e-ac226d553130.png">
> This now properly opens VSCode on the correct line. However, right now I have the issue that VSCode keeps asking me if I want to open the link, even though I mark "Allow opening links without asking". If someone has a fix for that, would be appreciated.

vscode://file${projectPath}${filePath}:${line}:${column}

**Comment by infi-pc** [comment]
I have merged https://github.com/infi-pc/locatorjs/pull/129, released an extension, and just released a new lib version with this fix. Thanks to all involved for checking. 

Just a quick recap: It was caused by VSCode update, and the fix was to remove one `/` from the template URL to VSCode.

**Comment by lzw10168** [comment]
![1702954276584](https://github.com/infi-pc/locatorjs/assets/67814702/c52ed501-be1f-421d-a659-738fcb820133)

vscode://file/${projectPath}${filePath}:${line}:${column}

This configuration in vscode 1.85.0, chrome 120, is fine

**Comment by gabrielsoaresgsm** [comment]
vscode 1.85.1 no longer works
