### ISSUE TITLE
bug: Path Error in VS Code when using Locator.js

### ISSUE THREAD

**Issue by sushantkadam15** [infi-pc/locatorjs#128]
### Where the bug happens

- [X] Browser Extension

### your browser

Chrome

### Describe the bug

Locator.js was working fine previously but has now stopped functioning. 
Path: `vscode://file/${projectPath}${filePath}:${line}:${column}`

Here are the steps I've taken to resolve the issue:
- Reinstalled VS Code.
- Reinstalled the Locator.js extension.

After some investigation, I found the following error in the VS Code Window Log:
``` 2023-11-03 09:13:07.831 [error] [uncaught exception in main]: [UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//"): Error: [UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//") ```

I've been searching for a solution but haven't been able to find one. Any assistance would be greatly appreciated.

**Comment by devhiteshk** [comment]
Chrome has stopped support for auto-play feature

https://support.google.com/chrome/thread/207847413/chrome-doesn-t-respect-autoplay-policy-flag-anymore?hl=en

need for alternative way to open the vscode file 

#127 Same raised here

**Comment by flex-haegul** [comment]
I have same issue.

**Comment by sheetalsindhu** [comment]
I'm having same issue, asking for associated app but not navigating.

**Comment by antopolskiy** [comment]
This works as a fix: https://github.com/infi-pc/locatorjs/issues/127#issuecomment-1801180366

**Comment by infi-pc** [comment]
fixed in https://github.com/infi-pc/locatorjs/pull/129, thanks @sushantkadam15 for PR and @antopolskiy for debugging
