### ISSUE TITLE
Launched external handler for 'vscode://file//Users/linxianxi/Projects/tastien/maternal-pc/src/pages/logistics/waybill/index.tsx:420:23'.bug: 

### ISSUE THREAD

**Issue by linxianxi** [infi-pc/locatorjs#130]
### Where the bug happens

- [X] Browser Extension
- [ ] Library
- [ ] Other

### your browser

chrome

### Describe the bug

Launched external handler for 'vscode://file//Users/linxianxi/Projects/tastien/maternal-pc/src/pages/logistics/waybill/index.tsx:420:23'.

**Comment by devhyunjae** [comment]
https://github.com/microsoft/vscode/issues/198644

**Comment by infi-pc** [comment]
i believe this is the same bug as this: https://github.com/infi-pc/locatorjs/issues/130. Fixed by https://github.com/infi-pc/locatorjs/pull/129
