### ISSUE TITLE
Add support for VSCode-Insiders

### ISSUE THREAD

**Issue by nikitavoloboev** [infi-pc/locatorjs#17]

**Comment by eidam** [comment]
had the exact same issue, this worked for me as a temporary workaround

```
document.cookie = "LOCATOR_CUSTOM_LINK=vscode-insiders://file${projectPath}${filePath}:${line}:${column}; expires=18 Dec 2033 12:00:00 UTC; path=/";
```

**Comment by nikitavoloboev** [comment]
Where do I run this code?

**Comment by eidam** [comment]
Sorry, in the browser dev tools console

**Comment by nikitavoloboev** [comment]
That worked amazingly. Had to refresh the page though. Thank you.

Will leave the issue up as I want native support for it. ♥️

**Comment by infi-pc** [comment]
fixed with 1.0.5 of Extension, for library version it will be fixed as soon as I migrate the UI from extension to lib. Closing for now.

**Comment by lopugit** [comment]
Hi @infi-pc 

I'm still getting this issue after switching to vscode-insiders to try the copilot chat beta. 

I just get this message when option clicking sections. Do you have any idea how to fix it?

This extension is literally mind blowing by the way! Have been using it for months now.

Thank you! 

![Screen Shot 2023-05-29 at 6 55 47 pm](https://github.com/infi-pc/locatorjs/assets/13629190/add924a2-79b1-4abb-b69e-d70eb612167a)

**Comment by infi-pc** [comment]
Hi, you have to change the link template in Locator. In Browser Extension, the following screen will appear when you click on the extension. You can either change the link by rewriting the link from `vscode` to `vscode-insiders`, but there is also a button for it. 

![CleanShot 2023-05-31 at 14 18 56](https://github.com/infi-pc/locatorjs/assets/2264725/7a1b01ea-d320-4a01-8efe-dfc51fef7d92)

In the library version of Locator, you should have a similar input field when you click setting in the bottom left corner. 

I see that you have `vscode://` in the screenshot, so I believe this will help.

**Comment by victor-heliomar** [comment]
Hi. Thanks for the response. YEA that worked perfectly!. Thanks!
