### ISSUE TITLE
Remix support

### ISSUE THREAD

**Issue by infi-pc** [infi-pc/locatorjs#3]
We are waiting for a proper plugins support https://github.com/remix-run/remix/issues/717

**Comment by infi-pc** [comment]
solved mostly by Devtools API

**Comment by dotdev-nikolaj** [comment]
hi @infi-pc 

What do you mean solved by Devtools API?

I get this message when option clicking, it's getting the path right but for some reason won't open :O 

Kind regards 😀 

<img width="295" alt="Screen Shot 2023-05-31 at 5 11 27 pm" src="https://github.com/infi-pc/locatorjs/assets/134979630/09ced826-4f78-4db7-934a-625115b26060">
