### ISSUE TITLE
WSL2 Support

### ISSUE THREAD

**Issue by Newbie012** [infi-pc/locatorjs#30]
Currently, when trying to navigate to a file, vscode fails to find the file, since it looks for `vscode://home/...` while it actually should be (for my case `vscode://vscode-remote/wsl+Ubuntu/home/...`.

As a workaround, for now, I unpacked the extension and changed the prefix and it seems to be working.

But I believe allowing to change the pattern (`vscode://file${projectPath}${filePath}:${line}:${column}`) will be a better choice.

**Comment by Newbie012** [comment]
I'm embarrassed to say that I haven't noticed the custom option 🤦🤦‍♀️🤦‍♂️

This extension amazing by the way. Thanks for sharing it 🙂

**Comment by infi-pc** [comment]
no problem :) thank you for the issue anyway, now I know it can be a problem. 
It is a clear usability issue, I will try to fix it for the next users - probably make the input field clickable, and switch to the "Custom link" option when you click on it :)

**Comment by jdeniau** [comment]
For the record, if you work with SSH, you can configure the link as following:

```
vscode://vscode-remote/ssh-remote+configname${projectPath}${filePath}:${line}:${column}
```

with `configname` being the name of the config in your .ssh/config file  ("vader" in the following screenshot).

![image](https://github.com/infi-pc/locatorjs/assets/1398469/882882e1-8618-4431-9e0e-6e659d9aaad4)

@infi-pc I spend a lot of time finding how to construct the link, it may be useful to add a helper in the UI for remote configuration.

**Comment by LucasWang474** [comment]
> For the record, if you work with SSH, you can configure the link as following:
> 
> ```
> vscode://vscode-remote/ssh-remote+configname${projectPath}${filePath}:${line}:${column}
> ```
> 
> with `configname` being the name of the config in your .ssh/config file ("vader" in the following screenshot).
> 
> ![image](https://private-user-images.githubusercontent.com/1398469/255960096-882882e1-8618-4431-9e0e-6e659d9aaad4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNzY4OTYsIm5iZiI6MTcyNzI3NjU5NiwicGF0aCI6Ii8xMzk4NDY5LzI1NTk2MDA5Ni04ODI4ODJlMS04NjE4LTQ0MzEtOWUwZS02ZTY1OWQ5YWFhZDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjVUMTUwMzE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTM2MWZiYWI1ZTg1YjU5M2VmYTg5YzEwNjdiNWY4YmM1NGY3OTg5YzdhZDU4M2ZlZTdlNmUyOTljZWQ2N2M5ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.DKX6jpkVzhcXUOLd28hkcormmg5ht8yfzVK4vZnjKLY)
> 
> @infi-pc I spend a lot of time finding how to construct the link, it may be useful to add a helper in the UI for remote configuration.

[jdeniau](https://github.com/jdeniau), thank you so much!
This is the similar path I configed for my cursor.
<img width="464" alt="image" src="https://github.com/user-attachments/assets/55c59284-7316-4a4d-8e9b-34f85a69db1a">
