### ISSUE TITLE
[Feature request] Support custom domain

### ISSUE THREAD

**Issue by lightsound** [infi-pc/locatorjs#35]
Thanks for a great library!

I'm using [ngrok](https://ngrok.com/) and developing on a proxy domain. Currently locatorjs only supports localhost, but it would be nice to have support for custom domains.

**Comment by infi-pc** [comment]
Hi, it should not do any difference if you are on localhost or on ngrok address. I just tested it for both browser extension and for library version of Localhost and both works for me.

here is a testing video for the library version  :
https://user-images.githubusercontent.com/2264725/172550161-c96493a7-8ccf-43e7-8d7e-b90c90d1465b.mp4

(for the browser extension it works similarly)

I recommend checking 
https://github.com/infi-pc/locatorjs/blob/master/apps/extension/README.md#troubleshooting (in case of browser extension)
https://github.com/infi-pc/locatorjs/blob/master/readme-library.md (in case of a library version)

let me know if it helps or if there are some other issues.

**Comment by lightsound** [comment]
Thanks!
I will try it today.

**Comment by lightsound** [comment]
When I tried, I was able to use LocatorJS in Chrome, but not Brave. Brave's shields (like AdBlocker) are turned off. The problem not working with Brave is not related to this issue, so I'll close. 

Thank you for your help!
