### ISSUE TITLE
Doesn't work in Storybook

### ISSUE THREAD

**Issue by elektronik2k5** [infi-pc/locatorjs#36]
**Describe the bug**
Thanks for creating this amazing extension! It works perfectly when I run the app but not in Storybook. I have no idea whether the issue is with my specific project or not and I haven't tried troubleshooting in any way. I did check that the extensions work in Brave and Firefox in the app and neither browser works in Storybook.

** Browser **
 - Chrome
 - Firefox

** OS **
- Linux

** IDE **
- VSCode

**To Reproduce**
1. Install extension
2. Launch Storybook (with source maps on)
3. Alt+Click component in Storybook preview
4. Sometimes cursor changes, sometimes not. No red outline, no component names and clicking doesn't do anything.

**Expected behavior**
It should just work in exactly the same way.

**Screenshots**
n/a

**Additional context**
Happy to help with anything I can.

**Comment by infi-pc** [comment]
hey, I just tried it on Storybook and I see a combination of two problems. 1. it is in an iframe, and currently, Locator does not see into iframes 2. Storybook doesn't include `@babel/plugin-transform-react-jsx-self` and `@babel/plugin-transform-react-jsx-source` by default. 
I will fix the iframe issue on Locator next week and add some info on how to add the plugins to Storybook.

**Comment by infi-pc** [comment]
ok, iframe functionality is merged to master. It will take around a week to get into the extension in Chrome Web Store. 

About the Storybook part. I was able to fix it by adding
```
{
  "presets": ["@babel/preset-react"],
  "plugins": [
    "@babel/plugin-transform-react-jsx-self",
    "@babel/plugin-transform-react-jsx-source"
  ]
}
``` 
to `.storybook/.babelrc.json`  


here is some info for babel in Storybook if needed: https://storybook.js.org/docs/react/configure/babel

**Comment by infi-pc** [comment]
Fixed
with the browser extension, it might work out-of-the-box in some settings. In others it will need the babel plugin setting i posted above.

Here are complete setup instructions: https://www.locatorjs.com/install/react (see Storybook link)

And here is an alternative setup with data-id solution for cases where the out-of-the-box and manual setup doesn't work https://www.locatorjs.com/install/react-data-id?stack=Storybook
