### ISSUE TITLE
Hi, how  can we Integration of them 

### ISSUE THREAD

**Issue by sudongyuer** [infi-pc/locatorjs#43]
Hi i am the maintainer of this repo : https://github.com/sudongyuer/vite-plugin-react-inspector
A vite plugin to jump to the sourcecode by click the browser tag

**Comment by infi-pc** [comment]
Hi, @sudongyuer your plugin looks cool. I have no idea how to integrate. 
But for starter, I added "similar projects" section including your plugin here, so the community around this kind of tools is a bit more connected :)
