### ISSUE TITLE
Unnecessary recently opened file history in VSCode

### ISSUE THREAD

**Issue by makeryi** [infi-pc/locatorjs#58]
**Describe the bug**
When I use `@locator/runtime` in my project, it works well, but I found an annoying problem: after locating a file from the browser to VSCode, the VSCode recently opened files have an unnecessary history. I wonder whether there is a way to avoid this.

Or, maybe this is a VSCode problem :D

**Screenshots**
![CleanShot 2022-09-25 at 20 52 41@2x](https://user-images.githubusercontent.com/46524124/192144464-1728fa4e-0c22-4768-91bd-3d1a5a0ab514.png)
![CleanShot 2022-09-25 at 20 34 06@2x](https://user-images.githubusercontent.com/46524124/192143693-3d9272b1-0353-4198-81f4-a41522660bd3.png)

**Desktop (please complete the following information):**
 - Device: MacBook Pro 2021
 - OS: macOS 12.6
 - Browser: Chrome
 - Version: @locator/runtime@0.1.8

**Additional context**
By the way, I found the ways that locatorjs use to open files, maybe WebStorm has a similar problem.
<img width="860" alt="CleanShot 2022-09-25 at 20 49 35@2x" src="https://user-images.githubusercontent.com/46524124/192144332-564c4b59-ae0d-4e94-82bf-bc961418c65a.png">

**Comment by infi-pc** [comment]
hi, I would consider it more as a problem of VSCode. I am not sure if it is something solvable because going to the file is basically opening it :/

**Comment by makeryi** [comment]
OK. Thank you for your reply.
