### ISSUE TITLE
Is there support for IntelliJ?

### ISSUE THREAD

**Issue by OdysseasMas-lw** [infi-pc/locatorjs#59]
As the title suggests, can locatorJS work with IntelliJ?

**Comment by peauc** [comment]
It works well with Webstorm i'd assume you can make IntelliJ work pretty easily.

**Comment by infi-pc** [comment]
you can select Webstorm and then select "custom" to rewrite the URL template from `webstorm://` to `idea://` The same will probably work also with `phpstorm://`, `pycharm://` and other editors from JetBrains

https://user-images.githubusercontent.com/2264725/193998899-b00ca493-2ab4-4726-919c-4f9f63d90a21.mp4

**Comment by infi-pc** [comment]
currently no, but I will add `linePlusOne, columnPlusOne, lineMinusOne, columnMinusOne` variables, this +-1 corrections are quite common

**Comment by kodi** [comment]
Thank you **so much**!

**Comment by Igor2122** [comment]
@infi-pc hey, i am trying to configure it with IDEA but does not work 
here is the custom link i use 
idea://open?file=${projectPath}${filePath}&line=${line}&column=${column}
