### ISSUE TITLE
The path [...] does not exist on this computer error

### ISSUE THREAD

**Issue by alexbouchardd** [infi-pc/locatorjs#65]
**Your question**

I've been trying the chrome extension and love the idea. However, when I open any component, I get the following error: 
<img width="376" alt="Screen Shot 2022-10-13 at 1 34 37 PM" src="https://user-images.githubusercontent.com/2049224/195666584-5a3db405-d567-4989-aa7c-44ef8427070b.png">

I tried changing the path property in the extension to start from the user root `~/dev/...` but no luck.

How can I resolve this issue?

**Comment by infi-pc** [comment]
hi, it seems your project uses relative paths - you can add project path in "project settings" 

https://user-images.githubusercontent.com/2264725/196126720-046af386-3d71-4153-a3a1-357e18decc47.mp4

**Comment by alexbouchardd** [comment]
That worked! It wasn't obvious at all to me. Perhaps I missed something in the readme / docs. Thanks 👍

**Comment by infi-pc** [comment]
Yeah, it is not documented well. Most users have absolute paths, so it was not needed, but for this cases, I want to add it somehow more visibly to the UI

**Comment by igor-arkhipov** [comment]
How about Firefox? Seem in bottom left button is absent project settings option https://cln.sh/H8pUT4
