### ISSUE TITLE
bug: Confusing behaviour of "project/content" settings not overriding "browser/popup" settings

### ISSUE THREAD

**Issue by Strajk** [infi-pc/locatorjs#87]
### Where the bug happens

- [X] Browser Extension
- [ ] Library
- [ ] Other

### your browser

Chrome

### Describe the bug

* Installed the extension
* Noticed Project settings in the bottom left corner, and used it to set the editor to WebStorm
* 🧐 **BUT**, VSCode was still being used
* Only after debugging the source code, I've noticed that Browser settings take precedence
![Screen 2022-12-19 at 11 50 39](https://user-images.githubusercontent.com/697301/208409637-2d83eabc-3b43-407d-bcc8-878d3f408659.png)

https://user-images.githubusercontent.com/697301/208409672-03e36420-7bba-49aa-a625-b92f8bb5576e.mp4

### To reproduce

described above

### Additional information

<3

**Comment by infi-pc** [comment]
should be fixed by this https://github.com/infi-pc/locatorjs/commit/577122a9762374414c36929b3b35732f5e6fae46 and released both in the library and the extension. 

Closing, if you still have the problem feel free to reopen. 
And sorry for the late response - I was busy with work and family.

**Comment by Strajk** [comment]
thx <3 

![tenor-236052631](https://user-images.githubusercontent.com/697301/216555965-f0cb7226-9a38-4861-82fe-305d13e0af24.gif)
