### ISSUE TITLE
bug: Locator is adding data- blocks to elements that don't support it

### ISSUE THREAD

**Issue by solomon23** [infi-pc/locatorjs#89]
### Where the bug happens

- [ ] Browser Extension
- [X] Library
- [ ] Other

### Describe the bug

The material library has some elements that don't support the data- block because they don't output into the dom - when this happens the material library outputs errors into the browsers

https://github.com/mui/material-ui/issues/35358

### To reproduce

Make a page using the ClickAwayListener from the material library and notice you get errors in your page when using the locatorjs babel plugin

### Additional information

It could possibly be fixed on their side but they're pretty sure they're doing the right thing.  Maybe it can be fixed on this side

**Comment by infi-pc** [comment]
Hey, I have added an option "ignoreComponentNames" to babel config, so you can manually ignore components that can't take the data-* properties. 

for your use-case the fix will be adding this to your Babel config:
```
plugins: [
      [
        "@locator/babel-jsx/dist",
        {
          ignoreComponentNames: "ClickAwayListener",
        },
      ],
    ],
```

sorry for late response, I was too busy with work and family

**Comment by infi-pc** [comment]
to add some info. 
Sadly, during the babel processing, we don't have a reliable way how to figure out which props can go to the component and which not. Typescript could solve it, but that would be quite a complicated solution. For now the only way is to do it manually. 

Putting exact component names into the plugin config is now the one way. 

In the future, we could add some comment syntax similar to eslint-ignore or ts-ignore. Something like 
```
  <>
    {/* locator-ignore */}
    <SomeComponent/>
  </>
```

**Comment by solomon23** [comment]
This fixed me up - thanks so much - closing this
